### ISSUE TITLE
Make a Github pages site for the app

### ISSUE THREAD

**Issue by nodanaonlyzuul** [nodanaonlyzuul/kokomo-desktop#8]
## Domain

Some good names are:

| Domain           | Cost      |
|:-----------------|:----------|
| kokomo.style     | 6.88/yr   |
| kokomo.sucks     | 268.00/yr |
| kokomo.institute | 3.88/yr   |
| kokomo.tips      | 6.88/yr   |
| kokomo.expert    | 6.88/yr   |

## Design Vibe

MASSIVE HERO IMAGE OF MIKE LOVE OR OTHER BAD BEACH BOY.
Maybe animated gif of john stamos hamming it up on percussion?

Cool salmon colors - maybe autoplaying MIDI?

## Content

* Should link to downloadable executable (with MD5 signature) and source.
* Facebook and Twitter Preview Images & Tags
* Side by Side of download and source links

**Comment by hadro** [comment]
Looks great!
